//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Schema struct {
	ID           int32 `sql:"primary_key"`
	Name         string
	Input        []byte
	Output       []byte
	Organization int32
	Created      *time.Time
	Updated      *time.Time
}
