//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Version struct {
	ID           int32 `sql:"primary_key"`
	Name         string
	Organization int32
	Model        int32
	Schema       int32
	Created      *time.Time
	Updated      *time.Time
}
