//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Model = newModelTable("public", "model", "")

type modelTable struct {
	postgres.Table

	//Columns
	ID           postgres.ColumnInteger
	Name         postgres.ColumnString
	Organization postgres.ColumnInteger
	Created      postgres.ColumnTimestamp
	Updated      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ModelTable struct {
	modelTable

	EXCLUDED modelTable
}

// AS creates new ModelTable with assigned alias
func (a ModelTable) AS(alias string) *ModelTable {
	return newModelTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ModelTable with assigned schema name
func (a ModelTable) FromSchema(schemaName string) *ModelTable {
	return newModelTable(schemaName, a.TableName(), a.Alias())
}

func newModelTable(schemaName, tableName, alias string) *ModelTable {
	return &ModelTable{
		modelTable: newModelTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newModelTableImpl("", "excluded", ""),
	}
}

func newModelTableImpl(schemaName, tableName, alias string) modelTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		NameColumn         = postgres.StringColumn("name")
		OrganizationColumn = postgres.IntegerColumn("organization")
		CreatedColumn      = postgres.TimestampColumn("created")
		UpdatedColumn      = postgres.TimestampColumn("updated")
		allColumns         = postgres.ColumnList{IDColumn, NameColumn, OrganizationColumn, CreatedColumn, UpdatedColumn}
		mutableColumns     = postgres.ColumnList{NameColumn, OrganizationColumn, CreatedColumn, UpdatedColumn}
	)

	return modelTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Name:         NameColumn,
		Organization: OrganizationColumn,
		Created:      CreatedColumn,
		Updated:      UpdatedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
