name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  vendor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: Vendor
      run: |
        make vendor
        git diff --exit-code

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: Generate
      run: |
        make sql-gen -B
        make api/v1alpha1/v1alpha1.go -B
        git diff --exit-code

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: Lint
      run: |
        go mod tidy
        make lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: Build model-tracking
      run: make
    - name: Build container
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: ghcr.io/connylabs/model-tracking
    - name: Test
      run: make test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: Build
      run: make

  all-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: Build model-tracking for all Linux Architectures
      run: make all-build

  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: Build model-tracking
      run: make
    - name: Build container
      uses: docker/build-push-action@v4
      with:
        context: .

  push:
    if: github.event_name != 'pull_request'
    needs:
    - vendor
    - lint
    - test
    - build
    - all-build
    - container
    - generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: Build model-tracking for all Linux Architectures
      run: make all-build
    - name: Determine SHA
      id: sha
      run: echo "::set-output name=sha::$(git describe --always --tags --dirty)"
    - name: Build and push
      id: push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/arm64, linux/arm, linux/amd64
        tags: ghcr.io/connylabs/model-tracking:latest, ghcr.io/connylabs/model-tracking:${{ steps.sha.outputs.sha }}
    - name: Determine digest
      run: echo ${{ steps.push.outputs.digest }}
